#!/bin/bash
while getopts u:p:a:b:d:e:f: option
do
 case "${option}"
 in
 u)  USER=${OPTARG};;
 p)  PASS=${OPTARG};;
 a)  SERVER=${OPTARG};;
 b)  PORT=${OPTARG};;
 d)  PROFILE=${OPTARG};;
 e)  ENTNAME=${OPTARG};;
 f)  ENTDESC=${OPTARG};;
 esac
done
ENCODED="$(echo $USER:$PASS|base64)"

JSON='{
"DeploymentInfo":
{
"ProfileName":"'$PROFILE'",
"Action":"Deploy"
},
"EnterpriseDeployParams":
{
"SiebelEnterprise":"'$ENTNAME'",
"EnterpriseDesc":"'$ENTDESC'"
}
}'

echo
echo $JSON
echo

echo $JSON |  curl -v  -k -H "Content-Length: ${#JSON}"  \
 -H "Authorization: Basic $ENCODED" \
 -H "Content-Type: application/json" \
 -X POST \
https://$SERVER:$PORT/siebel/v1.0/cloudgateway/deployments/enterprises/ \
-d @-

