#!/bin/bash
while getopts u:p:a:b:d:e:f:h:i:l: option
do
 case "${option}"
 in
 u)  USER=${OPTARG};;
 p)  PASS=${OPTARG};;
 a)  SAIHOST=${OPTARG};;
 b)  SAIPORT=${OPTARG};;
 d)  PROFILE=${OPTARG};;
 e)  SRVNAME=${OPTARG};;
 f)  SRVDESC=${OPTARG};;
 h)  SRVHOST=${OPTARG};;
 i)  SRVPORT=${OPTARG};;
 l)  LANGS=${OPTARG};;
 esac
done
ENCODED="$(echo $USER:$PASS|base64)"

JSON='{
"DeploymentInfo":
{
"PhysicalHostIP":"'$SRVHOST':'$SRVPORT'",
"ProfileName":"'$PROFILE'",
"Action":"Deploy"
},
"ServerDeployParams":
{
"SiebelServer":"'$SRVNAME'",
"SiebelServerDesc":"'$SRVDESC'",
"DeployedLanguage":"'$LANGS'"
}
}'

echo
echo $JSON
echo

echo $JSON |  curl -v  -k -H "Content-Length: ${#JSON}"  \
 -H "Authorization: Basic $ENCODED" \
 -H "Content-Type: application/json" \
 -X POST \
https://$SAIHOST:$SAIPORT/siebel/v1.0/cloudgateway/deployments/servers/ \
-d @-

