#!/bin/bash

usage() { echo "Usage: $0 -v <directory to map for persistent volume> -w <docker network name>" 1>&2; exit 1; }

while getopts v:w: option
do
 case "${option}" in
  v)  VOL=${OPTARG};;
  w)  NETWORK=${OPTARG};;
  *)  usage;;
 esac
done

if [ -z "${VOL}" ] || [ -z "${NETWORK}" ]; then
    usage
fi

echo
set -x
docker network create ${NETWORK}

docker run \
	-d -it \
	-p 5500:5500 \
	-p 1521:1521 \
	--name oracle19c \
	-h oracle19c \
	-v ${VOL}:/opt/oracle/oradata \
    -e "DB_MEMORY=4GB" \
	-e "ORACLE_PWD=Oradoc_db1" \
	-e "ORACLE_SID=ORCLCDB" \
	--network ${NETWORK} \
	--network-alias oracle19c \
	container-registry.oracle.com/database/enterprise:19.3.0.0