#!/bin/bash

usage() { echo "Usage: $0 [-u <sai username>] [-p <sai password>] [-e <enterprise> ] [ -s <server> ] [-c <component>] [-m <mode>] [-a <sai host name>] [-b <sai https port>]" 1>&2; exit 1; }

while getopts u:p:a:b:c:m:e:s: option
do
 case "${option}"
 in
 u)  USER=${OPTARG};;
 p)  PASS=${OPTARG};;
 a)  SAIHOST=${OPTARG};;
 b)  SAIPORT=${OPTARG};;
 c)  COMP=${OPTARG};;
 m)  MODE=${OPTARG};;
 e)  ENT=${OPTARG};;
 s)  SES=${OPTARG};;

 esac
done

if [ -z "${USER}" ] || [ -z "${PASS}" ] || [ -z "${COMP}" ] || [ -z "${MODE}" ] || [ -z "${SAIHOST}" ] || [ -z "${SAIPORT}" ] || [ -z "${ENT}" ] || [ -z "${SES}" ] ; then
    usage
fi

ENCODED="$(echo -n $USER:$PASS|base64)"

JSON='{"Action":"'${MODE}' start"}'

echo
echo $JSON
echo

echo $JSON |  curl -v  -k -H "Content-Length: ${#JSON}"  \
 -H "Authorization: Basic $ENCODED" \
 -H "Content-Type: application/json" \
 -X POST \
https://$SAIHOST:$SAIPORT/siebel/v1.0/cloudgateway/enterprises/${ENT}/servers/${SES}/components/${COMP} \
-d @-

